name: Auto Patch APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool apksigner openjdk-11-jdk

      - name: Assemble APK from parts
        run: cat Free_Fire.8.apk.part* > "Free Fire.8.apk"

      - name: Decompile APK
        run: apktool d "Free Fire.8.apk" -o decompiled

      - name: Patch Files
        run: python3 patch.py

      - name: Rebuild APK
        run: apktool b decompiled --use-aapt2 -o patched_unsigned.apk

      - name: Sign APK
        run: |
          keytool -genkey -v -keystore release.keystore -alias key -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Android"
          apksigner sign --ks release.keystore --ks-pass pass:123456 patched_unsigned.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modded-APK
          path: patched_unsigned.apk
